https-portal:
  image: steveltn/https-portal:1
  ports:
    - '80:80'
    - '443:443'
  links:
    - server
  restart: always
  environment:
    DOMAINS: 'webrtc.flours.info -> http://server:55555'
    STAGE: 'staging'
    WEBSOCKET: 'true'
server:
  build: .
  restart: always
